# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 899171b64ee339224bd824260f7a24b4a5d49581e9ee7d427a4fb0e7b8b4c15c8d180e4e4063307ee8e53ea749a393036011b51d19335ab00741a4a12de4936f

test:
  secret_key_base: 49864fca0844db71919ed57a03136b24739582af08d3485a7832552aca2b8a45b0a8b15da77976f1d5859eb2c00e55862899370b247de59a6e33aaf19bd34eab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 62f4d1a35103d3f57b77b378b0e62f86eddd464f3d70ec8c474ef39a29600556b7ab5396e80384dc36207dc733033c26c35953748786e081777ec753ad1b0d1a